name: GitHub Pages

on:
  push:
    branches: ["master"]

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: ./nav-app/
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.REPO_PKEY }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: nav-app/package-lock.json

      - name: Install Node dependencies
        run: npm ci

      - name: Build Navigator
        run: npm run build -- --configuration production,googleAnalytics --aot=false --build-optimizer=false --base-href=https://clemiller.github.io/attack-navigator/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./nav-app/dist
